spring:
  profiles:
    active: dev

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8002
spring:
  application:
    name: plat-service
  profiles: test

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8001
spring:
  application:
    name: plat-service
  profiles: dev

    
