eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/   # 指向控制中心
  #显示id
  instance:
      prefer-ip-address: true

#表示当前此服务的端口
server:
  port: 8001
#此服务的名称
spring:
  application:
    name: PLAT-SERVICE

