eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true  #使用ip注册到注册中心
server:
  port: 9001
spring:
  application:
    name: AIGOU_ZUUL
zuul:
  routes:
    PLAT-SERVICE: /login/**
  ignored-services: "*"
  prefix: /aigou
